version: '3.7'

services:
  ui:
    build: ./ui
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./ui/src:/home/node/app/src
      - ./ui/public:/home/node/app/public
    networks:
      - react-ab-network

  api:
    build: ./api
    command: npm start
    restart: always
    env_file: ./api/node.prod.env
    volumes:
      - ./api/src:/home/node/app
      - /home/node/app/node_modules/
    ports:
      - "8080:8080"
    networks:
      - react-ab-network

  mongo:
    image: mongo
    restart: always
    env_file: ./db/mongo.prod.env
    expose:
      - "27017"
    networks:
      - react-ab-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: ./db/mongo.prod.env
    depends_on: [mongo]
    networks:
      - react-ab-network

networks:
  react-ab-network:
    name: react-ab-network
