version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: bash -c "/wait-for-it.sh --timeout=0 mongo:${MONGO_PORT} && npm start"
    container_name: react-ab_api
    depends_on: [mongo]
    env_file: ./prod.env
    networks:
      - react-ab-network
    ports:
      - "${API_PORT}:8080"
    restart: 'no'
    volumes:
      - ./api/src:/home/node/app
      - /home/node/app/node_modules/
      - /home/node/app/errors/

  mongo:
    container_name: react-ab_mongo
    env_file: ./prod.env
    expose:
      - "${MONGO_PORT}"
    image: mongo
    networks:
      - react-ab-network
    restart: 'no'
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/

  mongo-express:
    container_name: react-ab_mongo-express
    depends_on: [mongo]
    env_file: ./prod.env
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    networks:
      - react-ab-network
    restart: 'no'

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    container_name: react-ab_ui
    ports:
      - "${UI_PORT}:3000"
    networks:
      - react-ab-network
    restart: 'no'
    volumes:
      - ./ui/src:/home/node/app
      - ./ui/src/public:/home/node/app/public
      - /home/node/app/.next
      - /home/node/app/node_modules

networks:
  react-ab-network:
    name: react-ab-network
