version: '3.7'

services:
  api:
    build: ./api
    command: bash -c "/home/node/app/wait-for-it.sh --timeout=0 mongo:27017 && npm start"
    container_name: react-ab_api
    depends_on: [mongo]
    env_file: ./prod.env
    networks:
      - react-ab-network
    ports:
      - "8080:8080"
    restart: 'no'
    volumes:
      - ./api/src:/home/node/app/src
      - /home/node/app/src/node_modules/

  mongo:
    container_name: react-ab_mongo
    env_file: ./prod.env
    expose:
      - "27017"
    image: mongo
    networks:
      - react-ab-network
    restart: 'no'
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/

  mongo-express:
    container_name: react-ab_mongo-express
    depends_on: [mongo]
    env_file: ./prod.env
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - react-ab-network
    restart: 'no'

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    container_name: react-ab_ui
    ports:
      - "3000:3000"
    networks:
      - react-ab-network
    restart: 'no'
    volumes:
      - ./ui:/home/node/app
      - ./ui/public:/home/node/app/public
      - /home/node/app/.next

networks:
  react-ab-network:
    name: react-ab-network
