version: '3.7'

services:
  api:
    build: ./api
    command: bash -c "/home/node/app/wait-for-it.sh --timeout=0 mongo:27017 && npm run-script dev"
    depends_on: [mongo]
    env_file: ./dev.env
    networks:
      - react-ab-network
    ports:
      - "8080:8080"
      - "9229:9229"
    restart: 'no'
    volumes:
      - ./api/src:/home/node/app/src
      - /home/node/app/src/node_modules/

  mongo:
    env_file: ./dev.env
    expose:
      - "27017"
    image: mongo
    networks:
      - react-ab-network
    restart: 'no'
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/

  mongo-express:
    depends_on: [mongo]
    env_file: ./dev.env
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - react-ab-network
    restart: 'no'

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    networks:
      - react-ab-network
    restart: 'no'
    volumes:
      - ./ui/src:/home/node/app/src
      - ./ui/public:/home/node/app/public

  netdata:
    cap_add:
      - SYS_PTRACE
    image: netdata/netdata
    networks:
      - react-ab-network
    ports:
      - 19999:19999
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  react-ab-network:
    name: react-ab-network
