version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: bash -c "/wait-for-it.sh --timeout=0 mongo:${MONGO_PORT} && npm run-script dev"
    container_name: react-ab_api
    depends_on: [mongo]
    env_file: ./dev.env
    networks:
      - react-ab-network
    ports:
      - "${API_PORT}:8080"
      - "${API_DEBUG_PORT}:9229"
    restart: 'no'
    volumes:
      - ./api/src:/home/node/app
      - /home/node/app/node_modules/

  mongo:
    container_name: react-ab_mongo
    env_file: ./dev.env
    expose:
      - "${MONGO_PORT}"
    image: mongo:6.0.1
    networks:
      - react-ab-network
    restart: 'no'
    volumes:
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro

  mongo-express:
    container_name: react-ab_mongo-express
    depends_on: [mongo]
    env_file: ./dev.env
    image: ghcr.io/blackthornyugen/mongo-express-docker:v1.0.0 # https://github.com/mongo-express/mongo-express/issues/887
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    networks:
      - react-ab-network
    restart: 'always'

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: react-ab_ui
    environment:
      - API_PORT=${API_PORT}
    ports:
      - "${UI_PORT}:3000"
      - "${UI_DEBUG_PORT}:9229"
    networks:
      - react-ab-network
    restart: 'no'
    volumes:
      - ./ui/src:/home/node/app
      - ./ui/src/public:/home/node/app/public
      - /home/node/app/.next
      - /home/node/app/node_modules

networks:
  react-ab-network:
    name: react-ab-network
